# If DATABASE_URL exists (Cloud), use it. Otherwise, use local Postgres.
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/pinewoods_golf}
spring.datasource.username=${DB_USER:golfAdmin}
spring.datasource.password=${DB_PASS:p}

# This ensures the app listens to the port Koyeb assigns it
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
# Change to 'never' or 'none' in production later, but for PoC 'always' is fine 
# if you want to ensure tables are created.
spring.sql.init.mode=always